version: '3'
services:
  tts_server:
    image: crpi-6ty60rr45g7d9i1q.cn-shanghai.personal.cr.aliyuncs.com/gmaui000/tts_server
    restart: always
    ports:
      - "40000:40004"
    volumes:
      - ./logs:/work/logs
    networks:
      tts:
        ipv4_address: 10.10.1.11
    restart: always

networks:
  tts:
    external: false
    name: tts_network
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/16
          gateway: 10.10.1.1
